# Generated by Django 6.1.1 on 2026-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('management', 'Management'), ('principal', 'Principal'), ('hr', 'HR'), ('academic_coordinator', 'Academic Coordinator'), ('department_head', 'Department Head'), ('viewer_auditor', 'Viewer/Auditor'), ('staff', 'Staff'), ('facility_manager', 'Facility Manager'), ('store_manager', 'Store Manager')], max_length=50, unique=True),
        ),
    ]
