# Generated by Django 5.0.14 on 2026-08-17 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('admission_no', models.CharField(max_length=100, unique=True)),
                ('grade', models.CharField(blank=True, choices=[('KG-1', 'KG - 1'), ('KG-2', 'KG - 2'), ('GRADE-1', 'Grade - 1'), ('GRADE-2', 'Grade - 2'), ('GRADE-3', 'Grade - 3'), ('GRADE-4', 'Grade - 4'), ('GRADE-5', 'Grade - 5'), ('GRADE-6', 'Grade - 6'), ('GRADE-7', 'Grade - 7'), ('GRADE-8', 'Grade - 8'), ('GRADE-9', 'Grade - 9'), ('GRADE-10', 'Grade - 10'), ('GRADE-11', 'Grade - 11'), ('GRADE-12', 'Grade - 12')], max_length=20)),
                ('division', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
