# Generated by Django 5.0.14 on 2026-08-15 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('emp_no', models.CharField(max_length=100, unique=True)),
                ('qatar_id', models.CharField(blank=True, max_length=100)),
                ('sponsor_status', models.CharField(blank=True, max_length=50)),
                ('home_country_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=100)),
                ('doj', models.DateField(blank=True, null=True)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('teaching_other_section', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('other_section_details', models.TextField(blank=True)),
                ('ug_qualification', models.CharField(blank=True, max_length=255)),
                ('pg_qualification', models.CharField(blank=True, max_length=255)),
                ('other_diploma', models.CharField(blank=True, max_length=255)),
                ('bed_qualified', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('bed_details', models.CharField(blank=True, max_length=255)),
                ('med_qualified', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('med_details', models.CharField(blank=True, max_length=255)),
                ('phd_qualified', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('position', models.CharField(blank=True, choices=[('KG', 'KG'), ('PRT', 'PRT'), ('TGT', 'TGT'), ('PGT', 'PGT'), ('OTHER', 'Other')], max_length=50)),
                ('experience_iis', models.CharField(blank=True, max_length=20)),
                ('experience_overall', models.CharField(blank=True, max_length=20)),
                ('class_teacher', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('class_teacher_grade_division', models.CharField(blank=True, max_length=255)),
                ('total_periods', models.PositiveIntegerField(blank=True, null=True)),
                ('continue_service', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10)),
                ('discontinue_reason', models.TextField(blank=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherGradeDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('KG-1', 'KG - 1'), ('KG-2', 'KG - 2'), ('GRADE-1', 'Grade - 1'), ('GRADE-2', 'Grade - 2'), ('GRADE-3', 'Grade - 3'), ('GRADE-4', 'Grade - 4'), ('GRADE-5', 'Grade - 5'), ('GRADE-6', 'Grade - 6'), ('GRADE-7', 'Grade - 7'), ('GRADE-8', 'Grade - 8'), ('GRADE-9', 'Grade - 9'), ('GRADE-10', 'Grade - 10'), ('GRADE-11', 'Grade - 11'), ('GRADE-12', 'Grade - 12')], max_length=20)),
                ('division', models.CharField(blank=True, max_length=10)),
                ('periods_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_divisions', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'grade', 'division')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periods_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_periods', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_periods', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
