# Generated by Django 5.0.14 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
