# Generated by Django 6.1 on 2026-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sponsor_status',
            field=models.CharField(blank=True, choices=[('SPONSORED', 'Sponsored'), ('NON_SPONSORED', 'Non-Sponsored')], max_length=20),
        ),
    ]
