# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0003_teacher_shift_alter_teacher_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section_type',
            field=models.CharField(
                blank=True,
                max_length=20,
                choices=[
                    ('BOYS', 'Boys Section'),
                    ('GIRLS', 'Girls Section'),
                    ('JUNIOR', 'Junior Section'),
                    ('KG', 'KG Section'),
                ],
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_coordinator',
            field=models.CharField(
                blank=True, max_length=10, choices=[('YES', 'Yes'), ('NO', 'No')],
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_hod',
            field=models.CharField(
                blank=True, max_length=10, choices=[('YES', 'Yes'), ('NO', 'No')],
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hod_subject',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hods',
                to='subjects.subject',
            ),
        ),
        migrations.AddField(
            model_name='teacher',
            name='leadership_role',
            field=models.CharField(
                blank=True,
                max_length=20,
                choices=[
                    ('VP', 'Vice Principal'),
                    ('HM', 'Headmaster / Headmistress'),
                    ('AHM', 'Assistant Headmaster / Headmistress'),
                ],
            ),
        ),
    ]
