# Generated by Django 6.1.1 on 2026-09-10 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_subject_required_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolManpowerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_teacher_ratio_target', models.DecimalField(decimal_places=2, default=28, max_digits=5)),
                ('default_class_capacity', models.PositiveIntegerField(default=28)),
                ('standard_teacher_periods', models.PositiveIntegerField(default=30)),
                ('workload_warning_percentage', models.PositiveIntegerField(default=101)),
                ('workload_critical_percentage', models.PositiveIntegerField(default=116)),
                ('class_capacity_warning_percentage', models.PositiveIntegerField(default=86)),
                ('contract_expiry_warning_days', models.PositiveIntegerField(default=90)),
                ('qid_expiry_warning_days', models.PositiveIntegerField(default=60)),
                ('ratio_warning_margin', models.DecimalField(decimal_places=2, default=2, help_text='Ratio points above target that count as WARNING before CRITICAL.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School manpower settings',
                'verbose_name_plural': 'School manpower settings',
            },
        ),
        migrations.CreateModel(
            name='GradeDivision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('KG-1', 'KG - 1'), ('KG-2', 'KG - 2'), ('GRADE-1', 'Grade - 1'), ('GRADE-2', 'Grade - 2'), ('GRADE-3', 'Grade - 3'), ('GRADE-4', 'Grade - 4'), ('GRADE-5', 'Grade - 5'), ('GRADE-6', 'Grade - 6'), ('GRADE-7', 'Grade - 7'), ('GRADE-8', 'Grade - 8'), ('GRADE-9', 'Grade - 9'), ('GRADE-10', 'Grade - 10'), ('GRADE-11', 'Grade - 11'), ('GRADE-12', 'Grade - 12')], max_length=20)),
                ('division', models.CharField(max_length=10)),
                ('section_type', models.CharField(blank=True, choices=[('BOYS', 'Boys Section'), ('GIRLS', 'Girls Section'), ('JUNIOR', 'Junior Section'), ('KG', 'KG Section')], max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_divisions', to='analytics.academicyear')),
            ],
            options={
                'ordering': ['grade', 'division'],
                'unique_together': {('academic_year', 'grade', 'division')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGradeRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('KG-1', 'KG - 1'), ('KG-2', 'KG - 2'), ('GRADE-1', 'Grade - 1'), ('GRADE-2', 'Grade - 2'), ('GRADE-3', 'Grade - 3'), ('GRADE-4', 'Grade - 4'), ('GRADE-5', 'Grade - 5'), ('GRADE-6', 'Grade - 6'), ('GRADE-7', 'Grade - 7'), ('GRADE-8', 'Grade - 8'), ('GRADE-9', 'Grade - 9'), ('GRADE-10', 'Grade - 10'), ('GRADE-11', 'Grade - 11'), ('GRADE-12', 'Grade - 12')], max_length=20)),
                ('periods_per_week', models.PositiveIntegerField(default=0)),
                ('section_type', models.CharField(blank=True, choices=[('BOYS', 'Boys Section'), ('GIRLS', 'Girls Section'), ('JUNIOR', 'Junior Section'), ('KG', 'KG Section')], max_length=20)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_grade_requirements', to='analytics.academicyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_requirements', to='subjects.subject')),
            ],
            options={
                'ordering': ['grade', 'subject__name'],
                'unique_together': {('academic_year', 'grade', 'subject', 'section_type')},
            },
        ),
    ]
