"use client";

import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getMe} from "@/lib/auth";
import {Appraisal,createAppraisal,createEmployee,EmployeeProfile,getAppraisals,getEmployees} from "@/lib/hr";

export default function EmployeeProfilesPage(){
 const router=useRouter();const [employees,setEmployees]=useState<EmployeeProfile[]>([]);const [appraisals,setAppraisals]=useState<Appraisal[]>([]);const [show,setShow]=useState(false);const [showAppraisal,setShowAppraisal]=useState(false);const [error,setError]=useState("");
 const [contractCutoff]=useState(()=>{const date=new Date();date.setDate(date.getDate()+60);return date.toISOString().slice(0,10);});
 const [form,setForm]=useState({employee_number:"",full_name:"",department:"",designation:"",employment_type:"full_time",status:"active",date_of_joining:"",contract_expiry:"",qatar_id:"",qatar_id_expiry:"",phone:"",email:"",emergency_contact:"",annual_leave_entitlement:"30"});
 const [review,setReview]=useState({employee:"",academic_year:"2026-27",performance_score:"",strengths:"",development_areas:"",goals:"",status:"draft",review_date:""});
 async function load(){const [a,b]=await Promise.all([getEmployees(),getAppraisals()]);setEmployees(a);setAppraisals(b);}
 useEffect(()=>{getMe().then(load).catch(()=>router.push("/login"));},[router]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await createEmployee({...form,annual_leave_entitlement:Number(form.annual_leave_entitlement)});setShow(false);await load();}catch{setError("Could not save employee profile. Check the employee number.");}}
 async function submitReview(e:FormEvent){e.preventDefault();try{await createAppraisal({...review,employee:Number(review.employee)} as unknown as Partial<Appraisal>);setShowAppraisal(false);await load();}catch{setError("Could not save appraisal. One review is allowed per academic year.");}}
 return <div className="aasr-page"><div className="aasr-page-header"><div><p className="aasr-eyebrow">Advanced HR</p><h1 className="aasr-page-title">Employee Profiles & Performance</h1><p className="aasr-page-subtitle">Employment, identity, contract, emergency contact, leave entitlement and appraisal records in one controlled HR workspace.</p></div><div className="aasr-actions"><button className="aasr-btn aasr-btn-secondary" onClick={()=>setShowAppraisal(!showAppraisal)}>+ Appraisal</button><button className="aasr-btn aasr-btn-primary" onClick={()=>setShow(!show)}>+ Employee Profile</button></div></div>
 <div className="brain-kpi-grid"><article className="brain-kpi"><span>Employee profiles</span><strong>{employees.length}</strong></article><article className="brain-kpi brain-kpi--success"><span>Active</span><strong>{employees.filter(x=>x.status==="active").length}</strong></article><article className="brain-kpi brain-kpi--warning"><span>Contracts due</span><strong>{employees.filter(x=>x.contract_expiry&&x.contract_expiry<=contractCutoff).length}</strong></article><article className="brain-kpi"><span>Appraisals</span><strong>{appraisals.length}</strong></article></div>
 {show&&<form onSubmit={submit} className="brain-panel brain-form-grid"><label>Employee number<input required value={form.employee_number} onChange={e=>setForm({...form,employee_number:e.target.value})}/></label><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Department<input required value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>Designation<input required value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></label><label>Employment type<select value={form.employment_type} onChange={e=>setForm({...form,employment_type:e.target.value})}><option value="full_time">Full Time</option><option value="part_time">Part Time</option><option value="contract">Contract</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="on_leave">On Leave</option><option value="inactive">Inactive</option></select></label><label>Date of joining<input type="date" value={form.date_of_joining} onChange={e=>setForm({...form,date_of_joining:e.target.value})}/></label><label>Contract expiry<input type="date" value={form.contract_expiry} onChange={e=>setForm({...form,contract_expiry:e.target.value})}/></label><label>Qatar ID<input value={form.qatar_id} onChange={e=>setForm({...form,qatar_id:e.target.value})}/></label><label>QID expiry<input type="date" value={form.qatar_id_expiry} onChange={e=>setForm({...form,qatar_id_expiry:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Emergency contact<input value={form.emergency_contact} onChange={e=>setForm({...form,emergency_contact:e.target.value})}/></label><label>Annual leave days<input type="number" min="0" value={form.annual_leave_entitlement} onChange={e=>setForm({...form,annual_leave_entitlement:e.target.value})}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Save Employee</button></div></form>}
 {showAppraisal&&<form onSubmit={submitReview} className="brain-panel brain-form-grid"><label>Employee<select required value={review.employee} onChange={e=>setReview({...review,employee:e.target.value})}><option value="">Select</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Academic year<input required value={review.academic_year} onChange={e=>setReview({...review,academic_year:e.target.value})}/></label><label>Score / 5<input required type="number" min="0" max="5" step="0.1" value={review.performance_score} onChange={e=>setReview({...review,performance_score:e.target.value})}/></label><label>Review date<input required type="date" value={review.review_date} onChange={e=>setReview({...review,review_date:e.target.value})}/></label><label className="brain-field-wide">Strengths<textarea value={review.strengths} onChange={e=>setReview({...review,strengths:e.target.value})}/></label><label className="brain-field-wide">Development areas<textarea value={review.development_areas} onChange={e=>setReview({...review,development_areas:e.target.value})}/></label><label className="brain-field-wide">Goals<textarea value={review.goals} onChange={e=>setReview({...review,goals:e.target.value})}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Save Appraisal</button></div></form>}
 {error&&<p className="brain-error">{error}</p>}<section className="aasr-section brain-table-wrap"><table className="aasr-table"><thead><tr><th>Employee</th><th>Department</th><th>Designation</th><th>Employment</th><th>Contract Expiry</th><th>QID Expiry</th><th>Leave Entitlement</th><th>Status</th></tr></thead><tbody>{employees.map(x=><tr key={x.id}><td><strong>{x.employee_number}</strong><br/><span className="brain-subtext">{x.full_name}</span></td><td>{x.department}</td><td>{x.designation}</td><td>{x.employment_type.replace("_"," ")}</td><td>{x.contract_expiry||"—"}</td><td>{x.qatar_id_expiry||"—"}</td><td>{x.annual_leave_entitlement} days</td><td><span className={`brain-status ${x.status==="active"?"brain-status--success":"brain-status--warning"}`}>{x.status.replace("_"," ")}</span></td></tr>)}{!employees.length&&<tr><td colSpan={8} className="aasr-empty-state">No employee profiles yet.</td></tr>}</tbody></table></section></div>;
}
