# Generated by Django 6.1 on 2026-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportstaff',
            name='age',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='bed_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='bed_qualified',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='contract_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='home_country_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='med_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='med_qualified',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='other_diploma',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='pg_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='phd_qualified',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='qatar_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='sponsor_status',
            field=models.CharField(blank=True, choices=[('SPONSORED', 'Sponsored'), ('NON_SPONSORED', 'Non-Sponsored')], max_length=20),
        ),
        migrations.AddField(
            model_name='transportstaff',
            name='ug_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
