# Generated by Django 6.1.1 on 2026-09-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportstaff_simplify_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportstaff',
            name='qatar_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
