"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getMe } from "@/lib/auth";
import { approvePolicyDocument, createDocumentCategory, createPolicyDocument, DocumentCategory, getDocumentCategories, getPolicyDocuments, PolicyDocument } from "@/lib/governance";

const TYPES=["policy","procedure","regulation","manual","standard","circular","form","other"];

export default function DocumentsPage(){
 const router=useRouter(); const [docs,setDocs]=useState<PolicyDocument[]>([]); const [categories,setCategories]=useState<DocumentCategory[]>([]); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [query,setQuery]=useState("");
 const [form,setForm]=useState({code:"",title:"",document_type:"policy",category:"",summary:"",owner_department:"",version:"1.0",status:"draft",effective_date:"",review_date:"",external_url:""}); const [file,setFile]=useState<File|null>(null);
 async function load(){const [a,b]=await Promise.all([getPolicyDocuments(),getDocumentCategories()]);setDocs(a);setCategories(b);}
 useEffect(()=>{getMe().then(load).catch(()=>router.push("/login"));},[router]);
 async function addCategory(){const name=window.prompt("Document category name");if(!name)return;await createDocumentCategory({name});await load();}
 async function submit(e:FormEvent){e.preventDefault();setError("");const data=new FormData();Object.entries(form).forEach(([k,v])=>{if(v)data.append(k,v)});if(file)data.append("file",file);try{await createPolicyDocument(data);setShow(false);await load();}catch{setError("Could not save the document. Check the document code and required fields.");}}
 const filtered=docs.filter(d=>`${d.code} ${d.title} ${d.summary} ${d.owner_department}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="aasr-page"><div className="aasr-page-header"><div><p className="aasr-eyebrow">Institutional Knowledge</p><h1 className="aasr-page-title">Policies & School Documents</h1><p className="aasr-page-subtitle">The authoritative repository for policies, procedures, regulations, standards, manuals, circulars and official forms.</p></div><div className="aasr-actions"><button className="aasr-btn aasr-btn-secondary" onClick={addCategory}>+ Category</button><button className="aasr-btn aasr-btn-primary" onClick={()=>setShow(!show)}>+ Add Document</button></div></div>
 <div className="brain-kpi-grid"><article className="brain-kpi"><span>Total documents</span><strong>{docs.length}</strong></article><article className="brain-kpi brain-kpi--success"><span>Approved</span><strong>{docs.filter(d=>d.status==="approved").length}</strong></article><article className="brain-kpi"><span>Under review</span><strong>{docs.filter(d=>d.status==="under_review").length}</strong></article><article className="brain-kpi brain-kpi--warning"><span>Review due</span><strong>{docs.filter(d=>d.review_date&&new Date(d.review_date)<=new Date()).length}</strong></article></div>
 {show&&<form onSubmit={submit} className="brain-panel brain-form-grid"><label>Document code<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="HR-POL-001"/></label><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Type<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{TYPES.map(t=><option key={t} value={t}>{t.replace("_"," ")}</option>)}</select></label><label>Category<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Select</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Owner department<input value={form.owner_department} onChange={e=>setForm({...form,owner_department:e.target.value})}/></label><label>Version<input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="under_review">Under Review</option><option value="approved">Approved</option><option value="archived">Archived</option></select></label><label>Effective date<input type="date" value={form.effective_date} onChange={e=>setForm({...form,effective_date:e.target.value})}/></label><label>Review date<input type="date" value={form.review_date} onChange={e=>setForm({...form,review_date:e.target.value})}/></label><label>External URL<input type="url" value={form.external_url} onChange={e=>setForm({...form,external_url:e.target.value})}/></label><label className="brain-field-wide">Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label className="brain-field-wide">Document file<input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Save Document</button></div></form>}
 {error&&<p className="brain-error">{error}</p>}<div className="aasr-filter-bar"><input className="aasr-input" placeholder="Search by code, title, department or content summary…" value={query} onChange={e=>setQuery(e.target.value)}/></div><section className="aasr-section brain-table-wrap"><table className="aasr-table"><thead><tr><th>Code / Title</th><th>Type</th><th>Department</th><th>Version</th><th>Effective</th><th>Review</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id}><td><strong>{d.code}</strong><br/><span className="brain-subtext">{d.title}</span></td><td>{d.document_type}</td><td>{d.owner_department||"—"}</td><td>{d.version}</td><td>{d.effective_date||"—"}</td><td>{d.review_date||"—"}</td><td><span className={`brain-status ${d.status==="approved"?"brain-status--success":d.status==="draft"?"":"brain-status--warning"}`}>{d.status.replace("_"," ")}</span></td><td>{d.status!=="approved"&&<button className="aasr-btn aasr-btn-secondary aasr-btn-sm" onClick={async()=>{await approvePolicyDocument(d.id);await load();}}>Approve</button>}</td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="aasr-empty-state">No matching school documents.</td></tr>}</tbody></table></section></div>;
}
