# Generated by Django 6.1.1 on 2026-09-16 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=60, unique=True)),
                ('full_name', models.CharField(max_length=180)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('employment_type', models.CharField(default='full_time', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('qatar_id', models.CharField(blank=True, max_length=30)),
                ('qatar_id_expiry', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=180)),
                ('annual_leave_entitlement', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='HRServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('noc', 'NOC'), ('employment_certificate', 'Employment Certificate'), ('salary_certificate', 'Salary Certificate'), ('id_renewal', 'Qatar ID Renewal'), ('contract_renewal', 'Contract Renewal'), ('other', 'Other')], max_length=40)),
                ('purpose', models.TextField()),
                ('required_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_hr', 'Pending HR'), ('pending_principal', 'Pending Principal'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending_hr', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='hr_management.employeeprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('emergency', 'Emergency'), ('unpaid', 'Unpaid')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='hr/leave/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_hos', 'Pending HOS'), ('pending_hr', 'Pending HR'), ('pending_principal', 'Pending Principal'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Correction')], default='pending_hos', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr_management.employeeprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HRAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hr_management.hrservicerequest')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hr_management.leaverequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppraisalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('strengths', models.TextField(blank=True)),
                ('development_areas', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='hr_management.employeeprofile')),
            ],
            options={
                'ordering': ('-review_date',),
                'unique_together': {('employee', 'academic_year')},
            },
        ),
    ]
