"use client";

import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getMe} from "@/lib/auth";
import {approveLeaveRequest,approveServiceRequest,createLeaveRequest,createServiceRequest,EmployeeProfile,getEmployees,getLeaveRequests,getServiceRequests,LeaveRequest,ServiceRequest} from "@/lib/hr";

export default function HRRequestsPage(){
 const router=useRouter();const [employees,setEmployees]=useState<EmployeeProfile[]>([]);const [leaves,setLeaves]=useState<LeaveRequest[]>([]);const [services,setServices]=useState<ServiceRequest[]>([]);const [mode,setMode]=useState<"leave"|"service"|null>(null);const [error,setError]=useState("");
 const [leave,setLeave]=useState({employee:"",leave_type:"annual",start_date:"",end_date:"",reason:""});const [service,setService]=useState({employee:"",request_type:"noc",purpose:"",required_by:""});
 async function load(){const [a,b,c]=await Promise.all([getEmployees(),getLeaveRequests(),getServiceRequests()]);setEmployees(a);setLeaves(b);setServices(c);}
 useEffect(()=>{getMe().then(load).catch(()=>router.push("/login"));},[router]);
 async function submitLeave(e:FormEvent){e.preventDefault();setError("");try{await createLeaveRequest({...leave,employee:Number(leave.employee)} as unknown as Partial<LeaveRequest>);setMode(null);await load();}catch{setError("Could not submit leave request. Check the dates and employee profile.");}}
 async function submitService(e:FormEvent){e.preventDefault();setError("");try{await createServiceRequest({...service,employee:Number(service.employee)} as unknown as Partial<ServiceRequest>);setMode(null);await load();}catch{setError("Could not submit HR service request.");}}
 return <div className="aasr-page"><div className="aasr-page-header"><div><p className="aasr-eyebrow">Employee Self-Service</p><h1 className="aasr-page-title">Leave & HR Services</h1><p className="aasr-page-subtitle">Leave: Staff → HOS → HR → Principal. Certificates and NOC: Staff → HR → Principal.</p></div><div className="aasr-actions"><button className="aasr-btn aasr-btn-secondary" onClick={()=>setMode("service")}>+ HR Service</button><button className="aasr-btn aasr-btn-primary" onClick={()=>setMode("leave")}>+ Leave Request</button></div></div>
 <div className="brain-kpi-grid"><article className="brain-kpi"><span>Leave requests</span><strong>{leaves.length}</strong></article><article className="brain-kpi brain-kpi--warning"><span>Leave pending</span><strong>{leaves.filter(x=>x.status.startsWith("pending")).length}</strong></article><article className="brain-kpi"><span>HR services</span><strong>{services.length}</strong></article><article className="brain-kpi brain-kpi--success"><span>Completed</span><strong>{services.filter(x=>x.status==="completed").length}</strong></article></div>
 {mode==="leave"&&<form onSubmit={submitLeave} className="brain-panel brain-form-grid"><label>Employee<select required value={leave.employee} onChange={e=>setLeave({...leave,employee:e.target.value})}><option value="">Select</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Leave type<select value={leave.leave_type} onChange={e=>setLeave({...leave,leave_type:e.target.value})}><option value="annual">Annual</option><option value="sick">Sick</option><option value="emergency">Emergency</option><option value="unpaid">Unpaid</option></select></label><label>Start date<input required type="date" value={leave.start_date} onChange={e=>setLeave({...leave,start_date:e.target.value})}/></label><label>End date<input required type="date" value={leave.end_date} onChange={e=>setLeave({...leave,end_date:e.target.value})}/></label><label className="brain-field-wide">Reason<textarea required value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Submit Leave</button></div></form>}
 {mode==="service"&&<form onSubmit={submitService} className="brain-panel brain-form-grid"><label>Employee<select required value={service.employee} onChange={e=>setService({...service,employee:e.target.value})}><option value="">Select</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label>Service<select value={service.request_type} onChange={e=>setService({...service,request_type:e.target.value})}><option value="noc">NOC</option><option value="employment_certificate">Employment Certificate</option><option value="salary_certificate">Salary Certificate</option><option value="id_renewal">Qatar ID Renewal</option><option value="contract_renewal">Contract Renewal</option><option value="other">Other</option></select></label><label>Required by<input type="date" value={service.required_by} onChange={e=>setService({...service,required_by:e.target.value})}/></label><label className="brain-field-wide">Purpose<textarea required value={service.purpose} onChange={e=>setService({...service,purpose:e.target.value})}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Submit Request</button></div></form>}
 {error&&<p className="brain-error">{error}</p>}<div className="brain-request-grid"><section><h2 className="brain-section-title">Leave Requests</h2>{leaves.map(x=><article className="brain-request-card" key={x.id}><div className="brain-request-card__head"><div><span>LEAVE-{x.id}</span><h2>{x.employee_name} · {x.leave_type}</h2></div><span className={`brain-status ${x.status==="approved"?"brain-status--success":""}`}>{x.status_label}</span></div><p>{x.reason}</p><div className="brain-meta"><span>{x.start_date} → {x.end_date}</span><span>{x.total_days} days</span></div><div className="brain-workflow"><span className="done">Submitted</span><span className={x.status!=="pending_hos"?"done":""}>HOS</span><span className={["pending_principal","approved"].includes(x.status)?"done":""}>HR</span><span className={x.status==="approved"?"done":""}>Principal</span></div><button disabled={!x.status.startsWith("pending")} className="aasr-btn aasr-btn-primary aasr-btn-sm" onClick={async()=>{await approveLeaveRequest(x.id);await load();}}>Approve Next</button></article>)}{!leaves.length&&<p className="aasr-empty-state brain-panel">No leave requests.</p>}</section><section><h2 className="brain-section-title">HR Services</h2>{services.map(x=><article className="brain-request-card" key={x.id}><div className="brain-request-card__head"><div><span>HR-{x.id}</span><h2>{x.employee_name} · {x.request_type_label}</h2></div><span className={`brain-status ${x.status==="completed"?"brain-status--success":""}`}>{x.status_label}</span></div><p>{x.purpose}</p><div className="brain-meta"><span>Required: {x.required_by||"Not specified"}</span></div><div className="brain-workflow"><span className="done">Submitted</span><span className={x.status!=="pending_hr"?"done":""}>HR</span><span className={x.status==="completed"?"done":""}>Principal</span></div><button disabled={!x.status.startsWith("pending")} className="aasr-btn aasr-btn-primary aasr-btn-sm" onClick={async()=>{await approveServiceRequest(x.id);await load();}}>Approve Next</button></article>)}{!services.length&&<p className="aasr-empty-state brain-panel">No HR service requests.</p>}</section></div></div>;
}
