"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getMe } from "@/lib/auth";
import { approveItemRequest, createItemRequest, getInventoryItems, getItemRequests, InventoryItem, issueItemRequest, ItemRequest, rejectItemRequest } from "@/lib/inventory";

export default function RequestsPage() {
  const router=useRouter(); const [items,setItems]=useState<InventoryItem[]>([]); const [requests,setRequests]=useState<ItemRequest[]>([]); const [show,setShow]=useState(false); const [busy,setBusy]=useState<number|null>(null); const [error,setError]=useState("");
  const [form,setForm]=useState({department:"",purpose:"",priority:"normal",item:"",quantity:"1",notes:"",requested_item_name:""});
  async function load(){const [a,b]=await Promise.all([getInventoryItems(),getItemRequests()]);setItems(a);setRequests(b);}
  useEffect(()=>{getMe().then(load).catch(()=>router.push("/login"));},[router]);
  async function submit(e:FormEvent){e.preventDefault();setError("");try{await createItemRequest({department:form.department,purpose:form.purpose,priority:form.priority,lines:[{item:form.item?Number(form.item):null,requested_item_name:form.requested_item_name,quantity:form.quantity,notes:form.notes}]});setShow(false);await load();}catch{setError("Could not submit the request.");}}
  async function act(id:number,type:"approve"|"reject"|"issue"){setBusy(id);try{if(type==="approve")await approveItemRequest(id);if(type==="issue")await issueItemRequest(id);if(type==="reject"){const c=window.prompt("Reason for rejection");if(c)await rejectItemRequest(id,c);}await load();}finally{setBusy(null);}}
  return <div className="aasr-page"><div className="aasr-page-header"><div><p className="aasr-eyebrow">Store Workflow</p><h1 className="aasr-page-title">Staff Item Requests</h1><p className="aasr-page-subtitle">Staff request → HOS → Facility Manager → Principal → Store issue, with a complete decision trail.</p></div><button className="aasr-btn aasr-btn-primary" onClick={()=>setShow(!show)}>+ New Request</button></div>
  {show&&<form onSubmit={submit} className="brain-panel brain-form-grid"><label>Department<input required value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">Normal</option><option value="urgent">Urgent</option></select></label><label>Catalogue item<select value={form.item} onChange={e=>setForm({...form,item:e.target.value})}><option value="">New / unlisted item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} ({i.stock_quantity} available)</option>)}</select></label><label>New item name<input value={form.requested_item_name} onChange={e=>setForm({...form,requested_item_name:e.target.value})} placeholder="Only if not listed"/></label><label>Quantity<input required type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Notes<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="brain-field-wide">Purpose / justification<textarea required value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label><div className="brain-form-actions"><button className="aasr-btn aasr-btn-primary">Submit Request</button></div></form>}
  {error&&<p className="brain-error">{error}</p>}<div className="brain-request-grid">{requests.map(r=><article className="brain-request-card" key={r.id}><div className="brain-request-card__head"><div><span>REQ-{String(r.id).padStart(4,"0")}</span><h2>{r.lines.map(l=>l.item_name||l.requested_item_name).join(", ")}</h2></div><span className={`brain-status ${r.status==="issued"?"brain-status--success":r.status==="rejected"?"brain-status--danger":""}`}>{r.status_label}</span></div><p>{r.purpose}</p><div className="brain-meta"><span>{r.department}</span><span>By {r.requester_name}</span><span>{new Date(r.created_at).toLocaleDateString()}</span></div><div className="brain-workflow"><span className="done">Submitted</span><span className={r.status!=="submitted"?"done":""}>HOS</span><span className={["facility_approved","principal_approved","issued"].includes(r.status)?"done":""}>Facility</span><span className={["principal_approved","issued"].includes(r.status)?"done":""}>Principal</span><span className={r.status==="issued"?"done":""}>Issued</span></div><div className="aasr-actions"><button disabled={busy===r.id||!["submitted","hos_approved","facility_approved"].includes(r.status)} className="aasr-btn aasr-btn-primary aasr-btn-sm" onClick={()=>act(r.id,"approve")}>Approve Next</button><button disabled={busy===r.id||r.status!=="principal_approved"} className="aasr-btn aasr-btn-secondary aasr-btn-sm" onClick={()=>act(r.id,"issue")}>Issue</button><button disabled={busy===r.id||["issued","rejected"].includes(r.status)} className="aasr-btn aasr-btn-danger aasr-btn-sm" onClick={()=>act(r.id,"reject")}>Reject</button></div></article>)}{!requests.length&&<p className="aasr-empty-state brain-panel">No requests submitted yet.</p>}</div></div>;
}
